---
- hosts: samba-dc
  remote_user: root
  roles:
    - compile
    - install
    - add_host_to_hosts_file
    - bind_backend
    - init_ad_domain
    - resolver_config
    - protect_resolv_conf    
    - systemd-unit
    - timesync
