---
# tasks file for systemd-unit

- name: Install systemd unit file
  copy: 
    src: "{{ item }}.service"
    dest: /etc/systemd/system/
  loop: "{{ unit_files }}"
    
- name: Reload systemd config
  systemd:
    daemon_reload: yes
    
- name: Start samba (to create /usr/local/samba/var/lib/ntp_signd/)
  service:
    name: "{{ item }}"
    state: started
  loop: "{{ unit_files }}"
   
- name: Stop samba
  service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ unit_files }}"

  
    