---
# tasks file for init_ad_domain

- name: Run AD DC provisioning
  command: "{{ ad_provision_command }}"

- name: Include Samba config in /etc/bind/named.conf
  lineinfile:
    path: /etc/bind/named.conf
    line: include "/usr/local/samba/bind-dns/named.conf";
  when: dns_backend == "BIND9_DLZ"
  notify: restart_bind

- name: Copy krb5.conf
  copy:
    src: /usr/local/samba/private/krb5.conf
    dest: /etc/krb5.conf
    remote_src: yes
    
- name: Setup dynamic DNS update using Kerberos
  lineinfile:
    path: /etc/bind/named.conf.options
    insertafter: 'options {'
    firstmatch: yes
    line: 'tkey-gssapi-keytab "/usr/local/samba/private/dns.keytab";'
    backup: yes

- name: Configure dynamic DNS update - fix private dir
  file: 
    path: /usr/local/samba/private
    group: bind
    mode: '750'
   
        